// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID           int64     `json:"id"`
	CustomerName string    `json:"customer_name"`
	Address      string    `json:"address"`
	CreatedAt    time.Time `json:"created_at"`
}

type Order struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	CustomerID int32     `json:"customer_id"`
	CreatedAt  time.Time `json:"created_at"`
	TotalPrice int32     `json:"total_price"`
	Cash       int32     `json:"cash"`
	Return     int32     `json:"return"`
}

type OrderDetail struct {
	ID        int64 `json:"id"`
	OrderID   int32 `json:"order_id"`
	ProductID int32 `json:"product_id"`
	Price     int32 `json:"price"`
	Quantity  int32 `json:"quantity"`
	Total     int32 `json:"total"`
}

type Product struct {
	ID           int64          `json:"id"`
	ProductName  string         `json:"product_name"`
	Price        int32          `json:"price"`
	ProductImage sql.NullString `json:"product_image"`
}

type Shop struct {
	ID          int64  `json:"id"`
	ShopName    string `json:"shop_name"`
	Address     string `json:"address"`
	PhoneNumber string `json:"phone_number"`
}

type User struct {
	Username       string         `json:"username"`
	HashedPassword string         `json:"hashed_password"`
	FullName       string         `json:"full_name"`
	Photo          sql.NullString `json:"photo"`
	CreatedAt      time.Time      `json:"created_at"`
}
