// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderDetail(ctx context.Context, arg CreateOrderDetailParams) (OrderDetail, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, username string) error
	GetProducts(ctx context.Context, id int64) (Product, error)
	ListCustomers(ctx context.Context) ([]Customer, error)
	ListOrder(ctx context.Context, username string) ([]Order, error)
	ListOrderDetails(ctx context.Context, orderID int32) ([]OrderDetail, error)
	ListProduct(ctx context.Context, arg ListProductParams) ([]Product, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
