// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: shop.sql

package db

import (
	"context"
)

const updateShop = `-- name: UpdateShop :one
UPDATE shops
SET shop_name = $1,
    address = $2,
    phone_number = $3
WHERE id = 1
RETURNING id, shop_name, address, phone_number
`

type UpdateShopParams struct {
	ShopName    string `json:"shop_name"`
	Address     string `json:"address"`
	PhoneNumber string `json:"phone_number"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error) {
	row := q.db.QueryRowContext(ctx, updateShop, arg.ShopName, arg.Address, arg.PhoneNumber)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.ShopName,
		&i.Address,
		&i.PhoneNumber,
	)
	return i, err
}
